version: '3.8'

services:
  postgres:
    image: 'postgres:13'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'

  wallet-api:
    depends_on:
      - postgres
    build: .
    command: bash start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/wallet-coin-api
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box:
