default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wallet_coin_api_development

test:
  <<: *default
  database: wallet_coin_api_test

production:
  <<: *default
  database: wallet_coin_api_production
  username: wallet_coin_api
  password: <%= ENV['WALLET_COIN_API_DATABASE_PASSWORD'] %>
